### PR TITLE
[cherry-pick][CDAP-20948] BQ Delta Replication Plugin Dataset Project Id Fix

### PR DESCRIPTION
**Pull request by shivamVarCS**
cherry-pick: #259

### CODE REVIEW

**Review by itsankit-google — CHANGES_REQUESTED** [review]
Please first raise a snapshot bump PR here: https://github.com/data-integrations/bigquery-delta-plugins/blob/ee801f13e06f78af37d2c23e2f3317b955cf7b6b/pom.xml#L25

We cannot release the same version again.

**Comment by shivamVarCS** [comment]
> Please first raise a snapshot bump PR here:
> 
> https://github.com/data-integrations/bigquery-delta-plugins/blob/ee801f13e06f78af37d2c23e2f3317b955cf7b6b/pom.xml#L25
> 
> We cannot release the same version again.

Raised and updated the PR

**Review by itsankit-google — COMMENTED** [review]
Please squash commits using rebase so that we can merge the PR.

**Comment by shivamVarCS** [comment]
Closing this PR, as a new PR to remove Snapshot version is created [PR](https://github.com/data-integrations/bigquery-delta-plugins/pull/264)

**Pull request closed without merging**
